stages:
  - "build:shared"
  - "build"
  # - "ship"

build:shared:
  image: node:12
  stage: build:shared
  before_script:
    - npm i -g typescript
  script:
    - cd shared
    - tsc -b -v
  artifacts:
    paths:
      - ./shared/dist
  tags:
    - docker

build:client:
  image: node:12
  stage: build
  before_script:
    - npm install -g @angular/cli
  script:
    - cd ./client-code
    - npm ci
    - ng build --prod
  dependencies:
    - build:shared
  artifacts:
    paths:
      - ./server-code/public
  tags:
    - docker

build:server:
  image: node:12
  stage: build
  script:
    - cd ./server-code
    - npm ci
    - npm run-script build
  dependencies:
    - build:shared
  artifacts:
    paths:
      - ./server-code/dist
    expire_in: 1 week
  tags:
    - docker

deploy:swarm:
  stage: deploy
  script:
    - docker-compose -f deploy.yml build
    - docker-compose -f deploy.yml push
    - docker stack deploy --compose-file deploy.yml vcgc19
  dependencies:
    - build:shared
    - build:client
    - build:server
  # only:
  #   - master
  tags:
    - jentner-swarm