version: '3'

services:
  app:
    image: 127.0.0.1:5000/vast-challenge-gc19:latest
    build:
      dockerfile: ./deployment/Dockerfile
      context: .
    environment:
      - DB_HOST=rethinkdb
      - DB_NAME=test
    depends_on: 
      - rethinkdb
    networks:
      - default
      - traefik-net
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=3000"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:vcgc19.dbvis.de"
        # username dbvis password beschte
        - "traefik.frontend.auth.basic=dbvis:$$apr1$$wGL9l34b$$V2ntdEolk36EnbCVwv0xw0"
        # enable compression: https://docs.traefik.io/v2.0/middlewares/compress/
        - "traefik.http.middlewares.test-compress.compress=true"

  rethinkdb:
    image: rethinkdb:2.3

  # postgresdb:
  #   image: kartoza/postgis:latest
  #   volumes:
  #     # will put the initscripts into the docker container and execute it automatically
  #     - ./postgresdb/initscripts/:/docker-entrypoint-initdb.d/
  #     # makes the postgres db persistent
  #     - postgres-data:/var/lib/postgresql
  #   environment:
  #     - POSTGRES_USER=vastchallenge
  #     - POSTGRES_PASS=vastchallenge
  #     - POSTGRES_DBNAME=vastchallenge
  #     # - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology # You can pass as many extensions as you need.
  #     # - ALLOW_IP_RANGE=all
  #     # - IP_LIST=*

volumes:
  postgres-data:

networks:
  default:
  traefik-net:
    external: true
