version: '3'

services:
  server:
    image: vast-challenge-gc19_server:latest
    build:
      dockerfile: ./Dockerfile
      context: ./server-code
    ports:
      - 3000:3000
    volumes:
      - ./server-code/:/app
    environment:
      - DB_HOST=rethinkdb #this must be the same name as the service name (line 27 of this file)
      - DB_NAME=test

  client:
    image: vast-challenge-gc19_client:latest
    build:
      dockerfile: ./Dockerfile
      context: ./client-code
    ports:
      - 4200:4200
    volumes:
      - ./client-code/:/app

  rethinkdb:
    image: rethinkdb:2.3
    ports:
      - 8080:8080 #admin interface

  postgresdb:
    image: kartoza/postgis:latest
    ports:
      - 5432:5432
    volumes:
      # will put the initscripts into the docker container and execute it automatically
      - ./postgresdb/initscripts/:/docker-entrypoint-initdb.d/
      # makes the postgres db persistent
      - postgres-data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=vastchallenge
      - POSTGRES_PASS=vastchallenge
      - POSTGRES_DBNAME=vastchallenge
      # - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology # You can pass as many extensions as you need.
      # - ALLOW_IP_RANGE=all
      # - IP_LIST=*

volumes:
  postgres-data:
