version: '3'

services:
  server:
    image: node:12-alpine
    ports:
      - 3000:3000
    volumes:
      - ./tsconfig.json:/app/tsconfig.json
      - ./shared:/app/shared
      - ./server-code/:/app/server-code
    working_dir: /app/server-code
    command: ["sh", "-c", "npm run-script start:watch"]
    # comment in this line below if you want to install the dependencies on every start
    #command: ["sh", "-c", "npm install && npm run-script start:watch"]
    environment:
      - DB_HOST=rethinkdb #this must be the same name as the service name (line 27 of this file)
      - DB_NAME=test
    depends_on: 
      - rethinkdb

  client:
    image: node:12-alpine
    ports:
      - 4200:4200
    volumes:
      - ./tsconfig.json:/app/tsconfig.json
      - ./shared:/app/shared
      - ./client-code/:/app/client-code
    working_dir: /app/client-code
    command: ["sh", "-c", "npm run-script start:docker"]
    # comment in this line below if you want to install the dependencies on every start
    #command: ["sh", "-c", "npm install && npm run-script start:docker"]

  rethinkdb:
    image: rethinkdb:2.3
    ports:
      - 8080:8080 #admin interface

  postgresdb:
    image: kartoza/postgis:latest
    ports:
      - 5432:5432
    volumes:
      # will put the initscripts into the docker container and execute it automatically
      - ./postgresdb/initscripts/:/docker-entrypoint-initdb.d/
      # makes the postgres db persistent
      - postgres-data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=vastchallenge
      - POSTGRES_PASS=vastchallenge
      - POSTGRES_DBNAME=vastchallenge
      # - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology # You can pass as many extensions as you need.
      # - ALLOW_IP_RANGE=all
      # - IP_LIST=*

volumes:
  postgres-data:
